{{- $enabled_configmap := .Values.configmap.enabled }}

{{- if $enabled_configmap }}
  {{- range $configmap := .Values.configmap.configs }}
---
apiVersion: v1
data:
  {{- if not (empty $configmap.filename) }}
  {{ $configmap.filename }}: |
{{ toYaml $configmap.file_content | indent 4 }}
  {{ end }}
  {{- with $configmap.env }}
{{ toYaml . | indent 2 }}
  {{- end }}
kind: ConfigMap
metadata:
  name: {{ $configmap.name }}
  namespace: {{ $configmap.namespace }}
  labels:
    name: {{ $configmap.name }}
  {{- end }}
{{- end }}
